ALTER TABLE `biblioteca`.`Libro` auto_increment = 1; 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('Blanca Nieves', 'lib/img/libros/Blanca Nieves/Portada.png',11); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('Caperucita Roja', 'lib/img/libros/Caperucita Roja/Portada.png',10); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('El arbol magico', 'lib/img/libros/El arbol magico/Portada.png',11); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('El robot desprogramado', 'lib/img/libros/El robot desprogramado/Portada.png',27); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('Hansel y Gretel', 'lib/img/libros/Hansel y Gretel/Portada.png',11); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('La cenicienta', 'lib/img/libros/La cenicienta/Portada.png',21); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('La nube avariciosa', 'lib/img/libros/La nube avariciosa/Portada.png',0); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('Libro de la selva', 'lib/img/libros/Libro de la selva/Portada.png',27); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('Los tres cerditos', 'lib/img/libros/Los tres cerditos/Portada.png',7); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('Rey leon', 'lib/img/libros/Rey leon/Portada.png',9); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('El genio chapuzas', 'lib/img/libros/El genio chapuzas/Portada.png',17); 
INSERT INTO `biblioteca`.`Libro` (`titulo`, `rutaPagina`,`cantPaginas`) VALUES ('El pirata bueno', 'lib/img/libros/El pirata bueno/Portada.png',13); 
SELECT * FROM biblioteca.Libro;